name: Cleanup preview branches
on:
  workflow_dispatch:
  schedule:
    # Run on Mondays at 5:45 UTC
    - cron: '45 5 * * 1'

jobs:
  cleanup-preview-branches:
    name: Cleanup preview branches
    runs-on: ubuntu-22.04
    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: python -m pip install --upgrade pip PyGithub
      - name: Run cleanup-script
        env:
          BEHEER: ${{ secrets.BEHEER }}
        run: |
          wget https://raw.githubusercontent.com/Logius-standaarden/Automatisering/main/scripts/cleanup-branches.py
          python cleanup-branches.py
      - name: Commit
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Remove obsolete preview branches
          commit_user_name: GitHub Actions
          commit_user_email: api@logius.nl
          commit_author: Standaardenbeheer <api@logius.nl>
